### ISSUE TITLE
Dataset region_isos is not  exhaustive

### ISSUE THREAD

**Issue by alaeddine-abbagh** [2DegreesInvesting/r2dii.data#160]
Even though it covers the majority of countries, The data set "region_isos" does not contain all requiered contries : if a company plant_location is not in "region_isos", that company won't be taken into account in the technology mix analysis.

**Comment by maurolepore** [comment]
Thanks @alaeddine-abbagh!

@jdhoffa, is this expected behaviour or a bug?

**Comment by jdhoffa** [comment]
This is expected behavior. @alaeddine-abbagh the region definitions in `region_isos` come directly from the corresponding scenario definitions (for example https://www.iea.org/reports/world-energy-outlook-2019). 

If a country has not been included in calculating the scenario projections, then the assets in that country should not be included for analysis. 

That said, the `global` region should include all country ISOs (in fact, the `global` category was defined using ISOs own list of all codes). Is there a code you see missing from the `global` region in particular?

**Comment by maurolepore** [comment]
Thanks @jdhoffa, I'll assume this closes the issue. But @alaeddine-abbagh feel free to answer @jdhoffa's question or make new comments. If necessary, we'll re-open.
