### ISSUE TITLE
remove `is_ultimate_owner` and `is_ultimate_listed_owner` from `ald_demo`

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#22]
Klaus has informed me that this data is from Bloomberg, and will not be provided to the banks. 
It is also not used at all in the analysis afaik. 

Quick fix, and not urgent, but helpful to ensure that the `ald` provided to the banks is as close as possible to the `ald_demo`

**Comment by jdhoffa** [comment]
Thanks @2diiKlaus

**Comment by maurolepore** [comment]
Thanks! I would do this sooner rather than later -- before we advertise r2dii.data. A fix that removes a thing always has the potential to break user's code.

Based on a quick search for [is_ultimate_owner](https://github.com/2DegreesInvesting/r2dii.data/search?q=is_ultimate_owner&unscoped_q=is_ultimate_owner) and [is_ultimate_listed_owner](https://github.com/2DegreesInvesting/r2dii.data/search?q=is_ultimate_listed_owner&unscoped_q=is_ultimate_listed_owner), it looks this fix only touches these files:
* [ ] data-raw/ald_demo.csv 
* [ ] data-raw/data_dictionary/ald_demo.csv
* [ ] R/ald_demo.csv 


Yet we may check for other potential edits based on the output of `r2dii.usethis::use_r2dii_data("ald_demo")`:

* [ ] Add "data-raw/ald_demo.csv" 
* [ ] Add "data-raw/data_dictionary/ald_demo.csv" 
* [ ] In "data-raw/ald_demo.R", add something like: 
  ```
  # Source: @<contributor> <URL to issue or pull request>
  ald_demo <- readr::read_csv(here::here("data-raw", "ald_demo.csv"))
  use_data(ald_demo, overwrite = TRUE)
  ```
* [ ] `usethis::use_r("ald_demo")`. Document `ald_demo` 
* [ ] `usethis::use_test("ald_demo")`. Add regression tests of `ald_demo` 
* [ ] `source("data-raw/data_dictionary.R"); devtools::load_all()` 
* [ ] `usethis::use_test("data_dictionary")`. Test `data_dictionary` includes `ald_demo`
