### ISSUE TITLE
update `region_isos` to include a `global` region

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.data#52]
- `region_isos` should have a meta `global` region which includes every unique iso (every country). 
- it should also have a column with the count of isos in each region (so that regions with the minimum number of countries can be used to determine globalaggregate)

**Comment by maurolepore** [comment]
@jdhoffa, RE your second dotpoint,
Instead of hard-coding the summary can we now calculate it on the fly wherever we need it with something like this?:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)

region_isos %>% count(region, sort = TRUE)
#> # A tibble: 25 x 2
#>    region                        n
#>    <chr>                     <int>
#>  1 non opec                    192
#>  2 non oecd                    170
#>  3 developing economies        165
#>  4 sub saharan africa           49
#>  5 central and south america    46
#>  6 europe                       43
#>  7 advanced economies           41
#>  8 asia pacific                 40
#>  9 developing asia              36
#> 10 oecd                         36
#> # … with 15 more rows

region_isos %>% add_count(region, sort = TRUE)
#> # A tibble: 1,057 x 4
#>    region   isos  source      n
#>    <chr>    <chr> <chr>   <int>
#>  1 non opec bg    weo2019   192
#>  2 non opec hr    weo2019   192
#>  3 non opec cy    weo2019   192
#>  4 non opec mt    weo2019   192
#>  5 non opec ro    weo2019   192
#>  6 non opec au    weo2019   192
#>  7 non opec at    weo2019   192
#>  8 non opec be    weo2019   192
#>  9 non opec ca    weo2019   192
#> 10 non opec cl    weo2019   192
#> # … with 1,047 more rows
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Adding the summary seems to belong downstream from the data. Hard coding the summary adds redundancy (because it can be calculated from the data),  and also it is prone to errors -- if a user removes a row for a country the hard-coded summary won't update.

In a way this is a problem similar to generating `ald_scenario_demo` from `ald_demo` and `scenario_demo`; it suggest we need a package that generates analysis-ready views from the normalized data. Maybe we can discuss today?

**Comment by jdhoffa** [comment]
Ya i tend to agree, I was adding the score as per Klaus' suggestions, but it is not my preference. Lets discuss today
